[package]
name = "polygon_search"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
